
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 15 23:31:38 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int BITWISE_AND = 27;
  public static final int ASSIGN_OP = 29;
  public static final int DIVIDE = 34;
  public static final int GREATER_OR_EQUAL = 39;
  public static final int INCREMENT = 19;
  public static final int CONST = 4;
  public static final int NAMESPACE = 3;
  public static final int RIGHT_SQUARE_BRACKET = 24;
  public static final int NOT_EQUAL = 37;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 43;
  public static final int BITWISE_OR = 28;
  public static final int LOWER_OR_EQUAL = 41;
  public static final int FOR = 18;
  public static final int MINUS = 32;
  public static final int DECREMENT = 20;
  public static final int SCOPE_OP = 30;
  public static final int GREATER_THAN = 38;
  public static final int STATIC = 5;
  public static final int COMMA = 12;
  public static final int CLASS = 50;
  public static final int RIGHT_PARENTHESIS = 26;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 33;
  public static final int LEFT_CURLY_BRACKET = 21;
  public static final int IF = 14;
  public static final int THIS = 49;
  public static final int IS_EQUAL = 36;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int LEFT_SQUARE_BRACKET = 23;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int SEMI_COLON = 11;
  public static final int IDENT = 42;
  public static final int BREAK = 16;
  public static final int VOID = 6;
  public static final int ARROW = 48;
  public static final int COLON = 46;
  public static final int ELSE = 15;
  public static final int READ = 7;
  public static final int EXTENDS = 47;
  public static final int MODULUS = 35;
  public static final int LOWER_THAN = 40;
  public static final int BOOL_CONST = 45;
  public static final int RIGHT_CURLY_BRACKET = 22;
  public static final int PRINT = 8;
  public static final int LEFT_PARENTHESIS = 25;
}

